spring:
  profiles.active: default

  application:
    name: RATINGSERVICE

  data:
    mongodb:
      uri: mongodb+srv://Tarun:Tarun123@cluster0.b1nvh5h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ratings

  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
