spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://Tarun:Tarun123@cluster0.b1nvh5h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ratings
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
